# josie's kitty conf

# shell - as it's best to leave bash as the login shell for Gentoo
shell /usr/bin/fish

# font settings
font_family monospace
font_size 12

# performance - repaint delay is for 100+ Hz, just in case I get a high refresh monitor eventually
repaint_delay 8 
sync_to_monitor yes

# window options
remember_window_size no
initial_window_width 110c
initial_window_height 52c
