# josie's gaming PC make.conf

# Regular flags:
WARNING_FLAGS="-Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"
COMMON_FLAGS="-march=alderlake -O3 -pipe -flto ${WARNING_FLAGS}"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS} ${LDFLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=alderlake"

# Additional flags for specific packages are in /etc/portage/env and /etc/portage/package.env

# Make options for 12600K (16t) and 32GB RAM (2GB per thread)
MAKEOPTS="-j16 -l24"
# uncomment both lines if using emerge default ops
#MAKEOPTS="-j8 -l20"
#EMERGE_DEFAULT_OPTS="--jobs 2 --load-average 6"

# accept all licenses except EULAs
ACCEPT_LICENSE="* -@EULA"

# USE flags
DONTUSE=" -telemetry -pulseaudio -qt5 -i915 -chromium -webengine -libreoffice -gtk -gnome -systemd -radeon -nouveau -dist-kernel"
DOUSE="sddm pipewire lm-sensors xwayland wayland dbus elogind qt6 dvd cdr vulkan mesa amdgpu networkmanager lto pgo vaapi firefox"
USE="${DONTUSE} ${DOUSE}"

CPU_FLAGS_X86="aes avx avx2 avx_vnni bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3 vpclmulqdq"
VIDEO_CARDS="amdgpu radeonsi"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8


GENTOO_MIRRORS="https://mirrors.kernel.org/gentoo/ \
    https://mirrors.mit.edu/gentoo-distfiles/ \
    https://mirror.rackspace.com/gentoo/"
